modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "aos.png"
authors = "${mod_authors}"
description = '''
Actions cost stamina: vanilla actions and other mods' actions (Paragliders, Better Combat, Combat Roll, Wall-Jump TXF). Uses Feathers of Fatigue when installed, or its own light stamina bar.
'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.compat.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "feathers_of_fatigue"
type = "optional"
versionRange = "${feathers_of_fatigue_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "paraglider"
type = "optional"
versionRange = "${paragliders_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "bettercombat"
type = "optional"
versionRange = "${bettercombat_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "combat_roll"
type = "optional"
versionRange = "${combatroll_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "walljump"
type = "optional"
versionRange = "${walljump_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
type = "optional"
versionRange = "${curios_range}"
ordering = "NONE"
side = "BOTH"
